### PR TITLE
Make ResourceFactory.readResource pluggable

### PR DESCRIPTION
**Pull request by jcassee**
Instead of trying to extend the existing JSON reader to implement issue #21, I elected to make the reader pluggable. This makes it possible to experiment with different renderers and readers.

I kept the original selector on the first character of the stream because it keeps the extension simple.

Usage:

``` java
resourceFactory.withReader('{', MyJsonResourceReader.class);
```

I added tests but no documentation, in order to conform to existing practices. ;-) Seriously, I would add some docs if there was some skeleton available.

### CODE REVIEW

**Comment by talios** [comment]
Hey, I've been thinking about this over the weekend and I keep coming back to the thought that exposing my cheap and nasty XML/JSON "test" is the wrong approach.  Not because it's cheap and nasty ( well, not ONLY because of that <g> ).

Mostly, the HAL spec only supports XML and JSON so we're not going to be matching on anything else, unless the spec grows.

I'm thinking, from the API point of view we want to make the readers/renderers for the supported media types pluggable, maybe along the lines of:

```
withReader(String mediaType, Reader reader)
```

This should throw an exception if the media type is unsupported, much like existing rendering of a resource.  Internally, we could just store the active reader/renderer for each type ( two maps, keys on media type ) and look the active one up inside the cheap and nasty selector.

**Comment by jcassee** [comment]
That sounds like a good idea, and easy to implement too. I'll update the
pull request.
Op 22 apr. 2012 07:37 schreef "Mark Derricutt" <
reply@reply.github.com>
het volgende:

**Comment by jcassee** [comment]
Updated with the new withReader signature. Looks better now. :-)

**Comment by talios** [comment]
Nice ;-) Cheers.

**Pull request merged**
