### PR TITLE
Rendering complex properties

### PR DESCRIPTION
**Pull request by ghost**
Hi,

This is probably worthy of some discussion to verify whether this is accepted/expected HAL behavior, but if HAL allows for resource properties to be arbitrarily complex structures (not just primitive string/number/bool stuff), then I should be able to build something like the below:

```
... in a JSON HAL document ...
  "age" : 33,
  "complexProperty" : {
    "fieldOne" : 1,
    "fieldTwo" : "hello",
    "fieldThree" : {
      "nestedFieldOne" : "hi"
    }
  },
  "expired" : false,
... 
```

The attached code allows for the rendering of complex properties in this way.  The JSON was easy, just adding the ObjectMapper to the renderer, Jackson serializes the POJOs without much effort.  The XML was a bit uglier.

This doesn't address the builder being able to read these sorts of properties in, only to render them.  I gave it a quick try, but that seems like a tougher nut to crack - maybe a decision needs to be made about what internal data format to deserialize both formats into, and then the readers do it that way and the renderers process that particular format.  Any thoughts on that?

### CODE REVIEW

**Comment by ghost** [comment]
Looking at the merges I did, I really made this ugly, didn't I?  I'm usually an SVN user, first time into git = not understanding that the final diff shown by the tool isn't the end-all.

I can refork and clean this submission up, if you like - or if you've had any thoughts about a good way to consume as well as produce properties like this, let me know and I can see about getting it implemented.

**Comment by ghost** [comment]
I'm going to try to clean this up a bit.  I'll submit a different pull request if I get it done.

**Comment by talios** [comment]
Cheers - look forward to seeing a new pull request ( just had someone else ask about this as well ). One of the main things I'm concerned about with this is the handling of round-tripping from object->representations->object again, and how the Interface based rendering will work.

**Comment by ghost** [comment]
I have a commit on my fork that allows complex properties to be used both during rendering and during reading:

  https://github.com/steveg103/halbuilder/commit/62c692698a3db4b944faa09dcfd9b03310d6837d

The basic strategy is to pull any complex property (POJO, basically) into a properties map using Jackson databinding, and work based off of that map at rendering time.

There are a couple of issues with it, though.  I wrote most of them down in comments on the ReaderResourceTest, which you can see in the commit.  It's mostly due to problems on the XML side.  When we're dealing with arbitrary, schemaless XML, we can't really say whether a field with value 1 is supposed to be a string, integer, etc, so the databinding libraries assume strings all the time, whereas on the JSON side, there's no ambiguity: "field" : 1 and "field" : "1" are concretely typed.  This inconsistency in typing is going to be an issue in two use cases I can think of:

1) Docs are read in from XML, and then output in JSON (the complex property values may be numbers, but they'll come out as strings)
2) Someone is trying to write a contract involving the complex properties

A couple of side issues/TODOs:
- Complex nil properties are coming out in XML as element/ instead of element xsi:nil="true"/
- There are a couple of new TODOs, having to do with processing arrays that may be part of the complex properties and with resolving isSatisfiedBy calls against complex properties

I wanted to put this up in my branch and let you have a look, in case you have any suggestions or thoughts.  I'm not really sure where to go with it from here - seems like around every turn is a landmine.  :)

**Comment by talios** [comment]
Hey steve, sorry I once again havn't got back to you sooner.  I like the direction you're going with here, it's quite similar to what I was thinking for a similar problem I was looking to address, I've pulled your branch into my local repo and am going to see if I can build upon it with the ideas I was already looking at for supporting custom object rendering/parsing ( i.e. supporting Date/Calendar/Joda-Time objects in a sensible fashion.

It's a long weekend break here in New Zealand so will be looking at this over the break.

**Pull request closed without merging**
